---
name: Run Unit Tests

on: 
  push :
    branches: master  

jobs:
  build:
    runs-on: ubuntu-latest
    test:
      name: Test Application 
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
          run : docker build -t temp/build

          
        -  name: deploy to repo
          uses: actions/checkout@v2
          run : 
            docker tag temp/build zkanto/excellerate:latest
            docker tag temp/build zkanto/excellerate:${{github.sha}}
            docker push zkanto/excellerate:latest
            docker push zkanto/excellerate:{{github.sha}}