---
name: Build Docker Image

on: 
  push :
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    test:
      name: Test Application 
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
          run : |
            cd node
            docker build -t temp/build

          
        -  name: deploy to repo
          uses: actions/checkout@v2
          run : |
            docker login --username zkanto --password 12345678@
            docker tag temp/build zkanto/excellerate:${{github.sha}}
            docker push zkanto/excellerate:{{github.sha}}