---
name: Build Docker Image

on:
 pull_request: 
  branches: master

jobs:
  deploy:
    name: Build Application
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go
        with: 
          go-version: 1.18.2
        run: 
          cd go
          go run
          go test

